window.HEATER_SIM_FLAGS = Object.freeze({
  robotSortingLogicLab: false,
  foundationsLab: true,
  pullResistorsLab: true,
  buttonDebouncingLab: false,
  variablesLab: false,
  variableTypesLab: true,
  memoryLayoutLab: true,
  asciiCharLab: true,
  numberRepresentationLab: false,
  conditionalsLab: true,
  loopsLab: true,
  adcLab: true,
  hysteresisLab: true,
  uartLab: true,
  i2cLab: true,
  functionsLab: true,
  interruptsLab: false,
  timersLab: true,
  stateMachinesLab: true,
  arduinoToFlowchart: false,

  gasWaterHeater: false,
  maze: true,
  ticTacToe: true,
  kitchenTimer: true,
  trafficLights: true,
  intersectionController: false,
  dualSevenSegment: true,
  coffeeMachine: false
});
